"""pony_hobbies_many_to_many

Revision ID: 1aac8b3304e5
Revises: 0001
Create Date: 2026-04-21 23:45:48.841474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1aac8b3304e5'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pony_hobbies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pony_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.ForeignKeyConstraint(['pony_id'], ['ponies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pony_id', 'hobby_id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_constraint(op.f('hobbies_pony_id_fkey'), 'hobbies', type_='foreignkey')
    op.drop_column('hobbies', 'pony_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hobbies', sa.Column('pony_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('hobbies_pony_id_fkey'), 'hobbies', 'ponies', ['pony_id'], ['id'])
    op.drop_table('pony_hobbies')
    # ### end Alembic commands ###
